export const WORKFLOW_STATES = {
  IDLE: "IDLE",
  LISTENING: "LISTENING",
  SYMPTOM_ANALYSIS: "SYMPTOM_ANALYSIS",
  KNOWLEDGE_RETRIEVAL: "KNOWLEDGE_RETRIEVAL",
  SEVERITY_ANALYSIS: "SEVERITY_ANALYSIS",
  SAFETY_VALIDATION: "SAFETY_VALIDATION",
  EMERGENCY_CHECK: "EMERGENCY_CHECK",
  RESPONSE_GENERATION: "RESPONSE_GENERATION",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export type WorkflowState = typeof WORKFLOW_STATES[keyof typeof WORKFLOW_STATES];
